feature(argus.backend.service.stats): Stats rework
scylladb/argus pull request #125
Opened 2022-05-25 13:37 UTC by k0machi

This commit reworks stats gathering mechanism, while keeping the legacy
one for now, while also adding this mechanism for ReleaseStats and
TestDashboard, which is now separate from stats and is an independent
component.
[Trello](https://trello.com/c/FSyZhMeV/5011-show-not-planned-jobs)

2022-05-25 14:37 UTC, roydahan commented
Putting this on-hold, till @k0machi will add few missing parts and be ready for deploy

2022-05-25 14:48 UTC, bentsi requested changes
need to remove old code (sidebar and release planner)

2022-05-29 09:49 UTC, bentsi commented on argus/backend/service/stats.py
> +        }
```suggestion
        self.status_map = {status: 0 for status in TestStatus}
```

2022-05-29 12:51 UTC, k0machi commented on argus/backend/service/stats.py
> +        }
Done

2022-06-02 12:40 UTC, bentsi approved these changes

2022-06-02 12:40 UTC, merged