improvement(events tab): show nemesis that happened
scylladb/argus pull request #229
Opened 2023-04-27 09:23 UTC by temichus

show which nemesis ran during each event
on events tab

![Screenshot from 2023-04-27 11-21-18](https://user-images.githubusercontent.com/1948660/234819181-83847a2d-57db-4637-9227-a643e11dc88f.png)
![Screenshot from 2023-04-27 11-21-09](https://user-images.githubusercontent.com/1948660/234819194-3bbfbafd-98ac-4ca6-8873-17d9eb86603d.png)

2023-04-27 12:24 UTC, aleksbykov approved these changes
LGTM, Small question

2023-04-27 12:24 UTC, aleksbykov commented on frontend/TestRun/EventsTab.svelte
> +                while(sortedNemesises[nemesisIndex]){
Do you need outer if statement? if sortedNemesises[nemesisInded] is false whille loop also will not run

2023-04-27 13:38 UTC, k0machi requested changes
Indendation for the while block is now offset, and some small comments about style.

2023-04-27 13:38 UTC, k0machi commented on frontend/TestRun/EventsTab.svelte
> +                while(sortedNemesises[nemesisIndex]){
You should correct the indentation of the while block and also fix spaces before `{` and after `}` characters (there should be a space in every case, e.g. `while (true) {`)

2023-04-27 13:38 UTC, k0machi commented on frontend/TestRun/EventsTab.svelte
> +    0
Looks like a typo here

2023-04-27 13:38 UTC, k0machi commented on frontend/TestRun/EventsTab.svelte
> +                    }else{
The `else` not needed as we break out in every other conditional, can just `nemesisIndex++` here.

2023-04-27 13:38 UTC, k0machi commented on frontend/TestRun/StructuredEvent.svelte
> +        <div class="ms-2 mb-2 rounded px-2 status-{event.nemesis.status.toLowerCase()}">{event.nemesis.name}</div>
The `div`s inside conditional blocks should be embedded.

2023-05-04 20:04 UTC, roydahan approved these changes

2023-05-05 13:01 UTC, merged