fix(client_service.py): Mark Passed runs as Investigated automatically
scylladb/argus pull request #321
Opened 2023-12-21 05:43 UTC by k0machi

This change adjusts the run status logic to automatically mark any run
that passed as investigated, as there's nothing to investigate.

Fixes #317

2023-12-21 05:50 UTC, fruch approved these changes
Lgtm

2023-12-21 09:25 UTC, roydahan requested changes
I disagree with the suggested behavior.

2023-12-21 09:33 UTC, mykaul commented
> I disagree with the suggested behavior.

Disagreeing is fine - please suggest an alternative though.

2023-12-21 09:53 UTC, roydahan commented
I wrote in the issue

2024-01-29 13:34 UTC, closed without merging

2024-01-29 13:34 UTC, k0machi commented
Closing as this is not needed.