improvement(frontend): Background stats fetching rework
scylladb/argus pull request #323
Opened 2023-12-21 07:07 UTC by k0machi

This commit changes the way Argus fetches release statistics in
background. Primary changes include:

* Workarea no longer fetches all release stats, instead only fetching
  release once when it is clicked. A button was added to refresh those
  stats manually to the release dropdown.

* Releases page no longer shows any stats

* Release Dashboard was optimized to only make 1 stats request per state
  change (version, background update) and now also contains a manual
  refresh button.

* Auto-refresh timers, where still applicable, were increased to 15-20
  minutes

* Background stats request will not fire now if the tab the request is
  being made from is not in focus

* Updating test run status now also updates the run selector.

* Both TestRun and TestRunSelector now contain a manual refresh button.
  Timers were increased for certain test types (with non-realtime data),
  SCT stays at 30 second refresh interval. Both also no longer fetch if
  tab is in the background.

Part of #293
Fixes #313

2023-12-21 07:08 UTC, k0machi commented
Demo:

![image](https://github.com/scylladb/argus/assets/7761415/fdf87141-78fd-458f-9196-b2919d1f5689)

![image](https://github.com/scylladb/argus/assets/7761415/d8cec8f0-6692-4512-b507-81806a314c93)
![image](https://github.com/scylladb/argus/assets/7761415/9d39758d-f6dd-4bd7-b82c-65bbc39094ff)
![image](https://github.com/scylladb/argus/assets/7761415/46a8cef4-84d5-432b-bd5d-b8b15a35a8a7)

2023-12-21 08:46 UTC, roydahan commented
Please do not merge without my review

2023-12-21 09:00 UTC, roydahan submitted a review, later dismissed
This is not a valid status

2023-12-21 09:24 UTC, k0machi commented
> This is not a valid status

is this about #322?

2023-12-21 09:26 UTC, roydahan commented
Yes, my mistake.
Fixing.

2023-12-26 07:12 UTC, fruch commented
@k0machi 
maybe nitpick, 

can we use the same icon in the workspace ? and align it to the right ?
cause it took me a few minutes to figure out where it is.

2023-12-26 07:14 UTC, fruch commented on frontend/TestRun/DriverMatrixTestRun.svelte
> -        }, 1000 * 30);
driver matrix is the last place we want auto refresh...

2023-12-26 07:19 UTC, fruch commented
@k0machi 

can we replace all the auto-timers to be with some button, we carefully think those case with auto-refresh, in most cases it's a waste of Argus time.

2023-12-27 00:29 UTC, roydahan commented
> This commit changes the way Argus fetches release statistics in background. Primary changes include:
> 
> * Workarea no longer fetches all release stats, instead only fetching
>   release once when it is clicked. A button was added to refresh those
>   stats manually to the release dropdown.
> * Releases page no longer shows any stats
Please revert this change, I like to see these stats there.
> * Release Dashboard was optimized to only make 1 stats request per state
>   change (version, background update) and now also contains a manual
>   refresh button.
> * Auto-refresh timers, where still applicable, were increased to 15-20
>   minutes
> * Background stats request will not fire now if the tab the request is
>   being made from is not in focus
> * Updating test run status now also updates the run selector.
> * Both TestRun and TestRunSelector now contain a manual refresh button.
>   Timers were increased for certain test types (with non-realtime data),
>   SCT stays at 30 second refresh interval. Both also no longer fetch if
>   tab is in the background.
> 
> Part of #293 Fixes #313

Many of the above changes aren't telling me much, I'm not sure what the new behaviour will be.
Let's have an online review of the new behaviour.

#

2023-12-27 00:31 UTC, roydahan requested changes
I would like to see a demo of the changes, I'm not sure I agree with all of them.

2024-01-15 11:28 UTC, k0machi commented
> > This commit changes the way Argus fetches release statistics in background. Primary changes include:
> > 
> > * Workarea no longer fetches all release stats, instead only fetching
> >   release once when it is clicked. A button was added to refresh those
> >   stats manually to the release dropdown.
> > * Releases page no longer shows any stats
> 
> Please revert this change, I like to see these stats there.
> 
> > * Release Dashboard was optimized to only make 1 stats request per state
> >   change (version, background update) and now also contains a manual
> >   refresh button.
> > * Auto-refresh timers, where still applicable, were increased to 15-20
> >   minutes
> > * Background stats request will not fire now if the tab the request is
> >   being made from is not in focus
> > * Updating test run status now also updates the run selector.
> > * Both TestRun and TestRunSelector now contain a manual refresh button.
> >   Timers were increased for certain test types (with non-realtime data),
> >   SCT stays at 30 second refresh interval. Both also no longer fetch if
> >   tab is in the background.
> > 
> > Part of #293 Fixes #313
> 
> Many of the above changes aren't telling me much, I'm not sure what the new behaviour will be. Let's have an online review of the new behaviour.

The changes in the second list are mostly performance optimizations, they don't change the experience much if at all. The demo for WorkArea and Release pages can be seen in the second comment of this PR, or do you want a recorded version of it?

@roydahan

2024-01-29 14:10 UTC, roydahan approved these changes

2024-01-29 15:19 UTC, merged