fix(ViewTypes.js): Add a fallback widget in case of undefined widgets
scylladb/argus pull request #503
Opened 2024-11-14 15:14 UTC by k0machi

This fix addresses a potential issue where a widget created on a newer
version of argus will cause an error on an older one when it is loaded
from the database.

2024-11-15 13:49 UTC, soyacz requested changes
need also to add support in View edit

2024-11-18 13:28 UTC, k0machi commented
> need also to add support in View edit

I think it would be for the best if we restrict view editing if an unsupported widget is found in the view definition. Show the error to the user and stop the edit process.

2024-11-18 13:53 UTC, k0machi commented
Demo:

![image](https://github.com/user-attachments/assets/2520441f-8a1a-4805-b20d-d0431203022a)

2024-11-18 15:00 UTC, soyacz commented
> > need also to add support in View edit
> 
> I think it would be for the best if we restrict view editing if an unsupported widget is found in the view definition. Show the error to the user and stop the edit process.

Cant we make it to be ignored? so we still can edit the others or remove unsupported one?

2024-11-18 15:44 UTC, k0machi commented
> > > need also to add support in View edit
> > 
> > 
> > I think it would be for the best if we restrict view editing if an unsupported widget is found in the view definition. Show the error to the user and stop the edit process.
> 
> Cant we make it to be ignored? so we still can edit the others or remove unsupported one?

I can add an "Edit anyway" button that will drop the unsupported widget

2024-11-18 17:23 UTC, soyacz commented
> > > > need also to add support in View edit
> > > 
> > > 
> > > I think it would be for the best if we restrict view editing if an unsupported widget is found in the view definition. Show the error to the user and stop the edit process.
> > 
> > 
> > Cant we make it to be ignored? so we still can edit the others or remove unsupported one?
> 
> I can add an "Edit anyway" button that will drop the unsupported widget

Yes, if can't just "ignore" it then better to have possibility to fix view in case it's needed.

2024-11-18 17:57 UTC, k0machi commented
@soyacz added the "Edit anyway" button.

![image](https://github.com/user-attachments/assets/a7b9ff9f-f719-4d92-a2a3-a178eda83b72)

2024-11-19 09:05 UTC, soyacz approved these changes
LGTM

2024-11-19 17:37 UTC, merged